"""add current_split_id, create workout_splits and split_days

Revision ID: 5f8747828a2b
Revises: 4c2a17f0afbc
Create Date: 2026-09-23 14:17:50.664837

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5f8747828a2b'
down_revision: Union[str, Sequence[str], None] = '4c2a17f0afbc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workout_splits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('split_days',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('split_id', sa.Integer(), nullable=False),
    sa.Column('day_of_week', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['split_id'], ['workout_splits.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('split_id', 'day_of_week')
    )
    op.add_column('users', sa.Column('current_split_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'users', 'workout_splits', ['current_split_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'current_split_id')
    op.drop_table('split_days')
    op.drop_table('workout_splits')
    # ### end Alembic commands ###
